-- Database schema for Parroquia - adapted from Codigo SQL ConRelaciones.sql
-- This runs in the existing parroquia_db database created by Docker

SET search_path TO pg_catalog,public;

-- object: public.tipo_identificacion | type: TABLE --
-- DROP TABLE IF EXISTS public.tipo_identificacion CASCADE;
CREATE TABLE public.tipo_identificacion (
	id_tipo_identificacion bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	descripcion character varying(255) NOT NULL,
	CONSTRAINT tipo_identificacion_pk PRIMARY KEY (id_tipo_identificacion)
);
-- ddl-end --
ALTER TABLE public.tipo_identificacion OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.tipo_identificacion (id_tipo_identificacion, descripcion) VALUES (E'1', E'Registro civil');
-- ddl-end --
INSERT INTO public.tipo_identificacion (id_tipo_identificacion, descripcion) VALUES (E'2', E'Tarjeta de identidad');
-- ddl-end --
INSERT INTO public.tipo_identificacion (id_tipo_identificacion, descripcion) VALUES (E'3', E'Contraseña');
-- ddl-end --
INSERT INTO public.tipo_identificacion (id_tipo_identificacion, descripcion) VALUES (E'4', E'Cedula');
-- ddl-end --
INSERT INTO public.tipo_identificacion (id_tipo_identificacion, descripcion) VALUES (E'5', E'Pasaporte');
-- ddl-end --
INSERT INTO public.tipo_identificacion (id_tipo_identificacion, descripcion) VALUES (E'6', E'NIT');
-- ddl-end --

-- object: public.estado_civil | type: TABLE --
-- DROP TABLE IF EXISTS public.estado_civil CASCADE;
CREATE TABLE public.estado_civil (
	id_estado_civil bigint NOT NULL,
	descripcion character varying(255) NOT NULL,
	CONSTRAINT estado_civil_pk PRIMARY KEY (id_estado_civil)
);
-- ddl-end --
ALTER TABLE public.estado_civil OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'1', E'Soltero');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'2', E'Soltera');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'3', E'Casado');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'4', E'Casada');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'5', E'Viudo');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'6', E'Viuda');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'7', E'Union libre');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'8', E'Divorciado');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'9', E'Divorciada');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'10', E'Padre cabeza de hogar');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'11', E'Madre cabeza de hogar');
-- ddl-end --
INSERT INTO public.estado_civil (id_estado_civil, descripcion) VALUES (E'12', E'Matrimonio religioso');
-- ddl-end --

-- object: public.parroquia | type: TABLE --
-- DROP TABLE IF EXISTS public.parroquia CASCADE;
CREATE TABLE public.parroquia (
	id_parroquia bigint NOT NULL,
	nombre character varying(255) NOT NULL,
	CONSTRAINT parroquia_pk PRIMARY KEY (id_parroquia)
);
-- ddl-end --
ALTER TABLE public.parroquia OWNER TO parroquia_user;
-- ddl-end --

-- object: public.parentesco | type: TABLE --
-- DROP TABLE IF EXISTS public.parentesco CASCADE;
CREATE TABLE public.parentesco (
	id_parentesco bigint NOT NULL,
	nombre character varying(255) NOT NULL,
	id_personas_personas bigint,
	CONSTRAINT parentesco_pk PRIMARY KEY (id_parentesco)
);
-- ddl-end --
ALTER TABLE public.parentesco OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'1', E'Abuelo');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'2', E'Abuela');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'3', E'Tio');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'4', E'Tia');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'5', E'Primo');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'6', E'Prima');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'7', E'Hermano');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'8', E'Hermana');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'9', E'Padre');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'10', E'Madre');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'11', E'Sobrino');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'12', E'Sobrina');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'13', E'Nieto');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'14', E'Nieta');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'15', E'Adoptado');
-- ddl-end --
INSERT INTO public.parentesco (id_parentesco, nombre) VALUES (E'16', E'Adoptada');
-- ddl-end --

-- object: public.tipo_viviendas | type: TABLE --
-- DROP TABLE IF EXISTS public.tipo_viviendas CASCADE;
CREATE TABLE public.tipo_viviendas (
	id_tipo_vivienda bigint NOT NULL,
	descripcion character varying(255),
	id_familia_familias bigint,
	CONSTRAINT tipo_vivienda_pk PRIMARY KEY (id_tipo_vivienda)
);
-- ddl-end --
ALTER TABLE public.tipo_viviendas OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.tipo_viviendas (id_tipo_vivienda, descripcion) VALUES (E'1', E'Propia');
-- ddl-end --
INSERT INTO public.tipo_viviendas (id_tipo_vivienda, descripcion) VALUES (E'2', E'Arrendada');
-- ddl-end --
INSERT INTO public.tipo_viviendas (id_tipo_vivienda, descripcion) VALUES (E'3', E'Familiar');
-- ddl-end --
INSERT INTO public.tipo_viviendas (id_tipo_vivienda, descripcion) VALUES (E'4', E'Invasion');
-- ddl-end --

-- object: public.tipos_disposicion_basura | type: TABLE --
-- DROP TABLE IF EXISTS public.tipos_disposicion_basura CASCADE;
CREATE TABLE public.tipos_disposicion_basura (
	id_tipos_disposicion_basura bigint NOT NULL,
	metodo character varying(255) NOT NULL,
	id_familia_familias bigint,
	CONSTRAINT tipos_disposicion_basura_pk PRIMARY KEY (id_tipos_disposicion_basura)
);
-- ddl-end --
ALTER TABLE public.tipos_disposicion_basura OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.tipos_disposicion_basura (id_tipos_disposicion_basura, metodo) VALUES (E'1', E'Al aire libre');
-- ddl-end --
INSERT INTO public.tipos_disposicion_basura (id_tipos_disposicion_basura, metodo) VALUES (E'2', E'Carro recolector');
-- ddl-end --
INSERT INTO public.tipos_disposicion_basura (id_tipos_disposicion_basura, metodo) VALUES (E'3', E'Compostaje');
-- ddl-end --
INSERT INTO public.tipos_disposicion_basura (id_tipos_disposicion_basura, metodo) VALUES (E'4', E'En tierra');
-- ddl-end --
INSERT INTO public.tipos_disposicion_basura (id_tipos_disposicion_basura, metodo) VALUES (E'5', E'Reciclaje');
-- ddl-end --

-- object: public.sistemas_acueducto | type: TABLE --
-- DROP TABLE IF EXISTS public.sistemas_acueducto CASCADE;
CREATE TABLE public.sistemas_acueducto (
	id_sistemas_acueducto bigint NOT NULL,
	proveedor character varying(255) NOT NULL,
	metodo_abastecimiento character varying(255) NOT NULL,
	descripcion character varying(255) NOT NULL,
	id_familia_familias bigint,
	CONSTRAINT sistemas_acueducto_pk PRIMARY KEY (id_sistemas_acueducto)
);
-- ddl-end --
ALTER TABLE public.sistemas_acueducto OWNER TO parroquia_user;
-- ddl-end --

-- object: public.tipos_aguas_residuales | type: TABLE --
-- DROP TABLE IF EXISTS public.tipos_aguas_residuales CASCADE;
CREATE TABLE public.tipos_aguas_residuales (
	id_tipos_aguas_residuales bigint NOT NULL,
	metodo character varying(255) NOT NULL,
	id_familia_familias bigint,
	CONSTRAINT tipos_aguas_residuales_pk PRIMARY KEY (id_tipos_aguas_residuales)
);
-- ddl-end --
ALTER TABLE public.tipos_aguas_residuales OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.tipos_aguas_residuales (id_tipos_aguas_residuales, metodo) VALUES (E'1', E'Alcantarillado');
-- ddl-end --
INSERT INTO public.tipos_aguas_residuales (id_tipos_aguas_residuales, metodo) VALUES (E'2', E'Al aire libre');
-- ddl-end --
INSERT INTO public.tipos_aguas_residuales (id_tipos_aguas_residuales, metodo) VALUES (E'3', E'Pozo septico');
-- ddl-end --
INSERT INTO public.tipos_aguas_residuales (id_tipos_aguas_residuales, metodo) VALUES (E'4', E'Quebradas');
-- ddl-end --

-- object: public.niveles_educativos | type: TABLE --
-- DROP TABLE IF EXISTS public.niveles_educativos CASCADE;
CREATE TABLE public.niveles_educativos (
	id_niveles_educativos bigint NOT NULL,
	nivel character varying(255) NOT NULL,
	id_personas_personas bigint,
	CONSTRAINT niveles_educativos_pk PRIMARY KEY (id_niveles_educativos)
);
-- ddl-end --
ALTER TABLE public.niveles_educativos OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'1', E'Primaria');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'2', E'Bachillerato');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'3', E'Pregrado');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'4', E'Posgrado');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'5', E'Maestria');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'6', E'Doctorado');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'7', E'Tecnico');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'8', E'Tecnologo');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'9', E'Sin estudios');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'10', E'Cursos');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'12', E'Diplomado');
-- ddl-end --
INSERT INTO public.niveles_educativos (id_niveles_educativos, nivel) VALUES (E'13', E'Seminario');
-- ddl-end --

-- object: public.sexo | type: TABLE --
-- DROP TABLE IF EXISTS public.sexo CASCADE;
CREATE TABLE public.sexo (
	id_sexo bigint NOT NULL,
	descripcion character varying(255) NOT NULL,
	CONSTRAINT sexo_pk PRIMARY KEY (id_sexo)
);
-- ddl-end --
ALTER TABLE public.sexo OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.sexo (id_sexo, descripcion) VALUES (E'1', E'Masculino');
-- ddl-end --
INSERT INTO public.sexo (id_sexo, descripcion) VALUES (E'2', E'Femenino');
-- ddl-end --

-- object: public.talla_vestimenta | type: TABLE --
-- DROP TABLE IF EXISTS public.talla_vestimenta CASCADE;
CREATE TABLE public.talla_vestimenta (
	id_talla_vestimenta bigint NOT NULL,
	descripcion character varying(255) NOT NULL,
	id_personas_personas bigint,
	CONSTRAINT talla_vestimenta_pk PRIMARY KEY (id_talla_vestimenta)
);
-- ddl-end --
ALTER TABLE public.talla_vestimenta OWNER TO parroquia_user;
-- ddl-end --

INSERT INTO public.talla_vestimenta (id_talla_vestimenta, descripcion) VALUES (E'1', E'L');
-- ddl-end --
INSERT INTO public.talla_vestimenta (id_talla_vestimenta, descripcion) VALUES (E'2', E'M');
-- ddl-end --
INSERT INTO public.talla_vestimenta (id_talla_vestimenta, descripcion) VALUES (E'3', E'S');
-- ddl-end --
INSERT INTO public.talla_vestimenta (id_talla_vestimenta, descripcion) VALUES (E'4', E'XL');
-- ddl-end --
INSERT INTO public.talla_vestimenta (id_talla_vestimenta, descripcion) VALUES (E'5', E'XS');
-- ddl-end --
INSERT INTO public.talla_vestimenta (id_talla_vestimenta, descripcion) VALUES (E'6', E'XXL');
-- ddl-end --

-- object: public.comunidades_culturales | type: TABLE --
-- DROP TABLE IF EXISTS public.comunidades_culturales CASCADE;
CREATE TABLE public.comunidades_culturales (
	id_comunidades_culturales bigint NOT NULL,
	descripcion character varying(255) NOT NULL,
	CONSTRAINT comunidades_culturales_pk PRIMARY KEY (id_comunidades_culturales)
);
-- ddl-end --
ALTER TABLE public.comunidades_culturales OWNER TO parroquia_user;
-- ddl-end --
