
services:
  # API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parroquia-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=parroquia_db
      - DB_USER=parroquia_user
      - DB_PASSWORD=ParroquiaSecure2025
      - JWT_SECRET=tu_jwt_secret_muy_seguro_de_al_menos_32_caracteres
      - JWT_REFRESH_SECRET=tu_refresh_secret_diferente_y_seguro
      - PORT=3000
    volumes:
      - app_logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - parroquia-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: parroquia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: parroquia_db
      POSTGRES_USER: parroquia_user
      POSTGRES_PASSWORD: ParroquiaSecure2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - parroquia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parroquia_user -d parroquia_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
networks:
  parroquia-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local