services:
  # PostgreSQL Database Only
  postgres:
    image: postgres:15-alpine
    container_name: parroquia-postgres-only
    restart: unless-stopped
    environment:
      POSTGRES_DB: parroquia_db
      POSTGRES_USER: parroquia_user
      POSTGRES_PASSWORD: "admin"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - parroquia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parroquia_user -d parroquia_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  parroquia-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local