INSERT INTO enfermedades (nombre, descripcion, "createdAt", "updatedAt") VALUES 
('Diabetes tipo 1', 'Enfermedad autoinmune en la cual el páncreas no produce insulina o produce muy poca cantidad.', NOW(), NOW()),
('Diabetes tipo 2', 'Trastorno metabólico caracterizado por altos niveles de glucosa en sangre debido a resistencia a la insulina.', NOW(), NOW()),
('Hipertensión arterial', 'Presión arterial elevada de forma sostenida por encima de los valores normales.', NOW(), NOW()),
('Asma bronquial', 'Enfermedad inflamatoria crónica de las vías respiratorias que causa dificultad para respirar.', NOW(), NOW()),
('Artritis reumatoide', 'Enfermedad autoinmune que causa inflamación crónica de las articulaciones.', NOW(), NOW()),
('Enfermedad cardiovascular', 'Grupo de trastornos que afectan el corazón y los vasos sanguíneos.', NOW(), NOW()),
('Epilepsia', 'Trastorno neurológico caracterizado por episodios recurrentes de convulsiones.', NOW(), NOW()),
('Depresión mayor', 'Trastorno del estado de ánimo caracterizado por sentimientos persistentes de tristeza y pérdida de interés.', NOW(), NOW()),
('Ansiedad generalizada', 'Trastorno de ansiedad caracterizado por preocupación excesiva y persistente.', NOW(), NOW()),
('Osteoporosis', 'Enfermedad en la que los huesos se vuelven frágiles y más propensos a fracturas.', NOW(), NOW()),
('Insuficiencia renal crónica', 'Pérdida gradual y permanente de la función renal a lo largo del tiempo.', NOW(), NOW()),
('Enfermedad pulmonar obstructiva crónica (EPOC)', 'Grupo de enfermedades pulmonares que obstruyen el flujo de aire y dificultan la respiración.', NOW(), NOW()),
('Hipotiroidismo', 'Condición en la que la glándula tiroides no produce suficientes hormonas tiroideas.', NOW(), NOW()),
('Hipertiroidismo', 'Condición en la que la glándula tiroides produce demasiadas hormonas tiroideas.', NOW(), NOW()),
('Cáncer de mama', 'Tipo de cáncer que se forma en los tejidos de la mama.', NOW(), NOW()),
('Cáncer de próstata', 'Tipo de cáncer que se desarrolla en la glándula prostática.', NOW(), NOW()),
('Migraña', 'Tipo de dolor de cabeza recurrente que puede ser severo y debilitante.', NOW(), NOW()),
('Fibromialgia', 'Trastorno caracterizado por dolor musculoesquelético generalizado.', NOW(), NOW()),
('Enfermedad de Alzheimer', 'Trastorno neurodegenerativo que causa problemas de memoria, pensamiento y comportamiento.', NOW(), NOW()),
('Enfermedad de Parkinson', 'Trastorno neurodegenerativo que afecta principalmente el movimiento.', NOW(), NOW()),
('Síndrome del intestino irritable', 'Trastorno gastrointestinal funcional que causa dolor abdominal y cambios en los hábitos intestinales.', NOW(), NOW()),
('Gastritis crónica', 'Inflamación prolongada del revestimiento del estómago.', NOW(), NOW()),
('Úlcera péptica', 'Llaga que se desarrolla en el revestimiento del estómago o duodeno.', NOW(), NOW()),
('Hepatitis B', 'Infección viral que ataca el hígado y puede causar enfermedad aguda y crónica.', NOW(), NOW()),
('Hepatitis C', 'Infección viral que causa inflamación del hígado y puede llevar a daño hepático grave.', NOW(), NOW()),
('VIH/SIDA', 'Virus de inmunodeficiencia humana que ataca el sistema inmunitario.', NOW(), NOW()),
('Tuberculosis', 'Infección bacteriana que afecta principalmente los pulmones.', NOW(), NOW()),
('Lupus eritematoso sistémico', 'Enfermedad autoinmune que puede afectar múltiples órganos y sistemas.', NOW(), NOW()),
('Esclerosis múltiple', 'Enfermedad autoinmune que afecta el sistema nervioso central.', NOW(), NOW()),
('Insuficiencia cardíaca', 'Condición en la que el corazón no puede bombear sangre de manera eficiente.', NOW(), NOW());
