#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║        📋 ANÁLISIS JENKINSFILE - CONFIGURACIÓN PROPUESTA                     ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 OBJETIVO:"
echo "   Configurar pipeline Jenkins para desplegar API Parroquia con Docker"
echo ""

echo "📊 SITUACIÓN ACTUAL:"
echo "   ✅ Jenkins corriendo en Ubuntu local"
echo "   ✅ Jenkinsfile existe (configurado para servidor remoto)"
echo "   ✅ Docker Compose con PostgreSQL activo"
echo "   ✅ Dockerfile multi-stage optimizado"
echo "   ⚠️  Servicio API comentado en docker-compose.yml"
echo "   ⚠️  Jenkinsfile apunta a servidor remoto 206.62.139.100"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo "🔄 DOS OPCIONES DE CONFIGURACIÓN:"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

echo "┌─ OPCIÓN A: DESPLIEGUE LOCAL (⭐ RECOMENDADO) ────────────────────────────────┐"
echo "│                                                                               │"
echo "│  Jenkins (Ubuntu) ──→ Git Checkout ──→ Docker Build ──→ Docker Deploy       │"
echo "│                                                                               │"
echo "│  ✅ Ventajas:                                                                 │"
echo "│     • Configuración más simple (sin SSH)                                     │"
echo "│     • Deploy más rápido (misma máquina)                                      │"
echo "│     • Menos puntos de fallo                                                  │"
echo "│     • Ideal para desarrollo/staging                                          │"
echo "│                                                                               │"
echo "│  ❌ Desventajas:                                                              │"
echo "│     • Jenkins y App comparten recursos                                       │"
echo "│     • No simula ambiente de producción real                                  │"
echo "│                                                                               │"
echo "│  📝 Cambios necesarios:                                                       │"
echo "│     1. Eliminar secciones SSH del Jenkinsfile                                │"
echo "│     2. Cambiar DEPLOY_BRANCH de 'feature' a 'develop'                        │"
echo "│     3. Descomentar servicio 'api' en docker-compose.yml                      │"
echo "│     4. Crear archivo .env con variables de entorno                           │"
echo "│     5. Configurar credenciales Git en Jenkins                                │"
echo "│                                                                               │"
echo "└───────────────────────────────────────────────────────────────────────────────┘"
echo ""

echo "┌─ OPCIÓN B: DESPLIEGUE REMOTO (Configuración actual) ────────────────────────┐"
echo "│                                                                               │"
echo "│  Jenkins (Local) ──→ SSH ──→ Servidor 206.62.139.100 ──→ Docker Deploy      │"
echo "│                                                                               │"
echo "│  ✅ Ventajas:                                                                 │"
echo "│     • Separación de ambientes (Jenkins vs Producción)                        │"
echo "│     • Jenkins no consume recursos de producción                              │"
echo "│     • Setup similar a producción real                                        │"
echo "│                                                                               │"
echo "│  ❌ Desventajas:                                                              │"
echo "│     • Requiere configurar SSH keys                                           │"
echo "│     • Más complejo de debuggear                                              │"
echo "│     • Deploy más lento (red de por medio)                                    │"
echo "│                                                                               │"
echo "│  📝 Cambios necesarios:                                                       │"
echo "│     1. Configurar SSH key en Jenkins                                         │"
echo "│     2. Cambiar DEPLOY_BRANCH de 'feature' a 'develop'                        │"
echo "│     3. Verificar usuario y ruta en servidor remoto                           │"
echo "│     4. Asegurar que .env existe en servidor remoto                           │"
echo "│     5. Configurar credenciales SSH en Jenkins                                │"
echo "│                                                                               │"
echo "└───────────────────────────────────────────────────────────────────────────────┘"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo "🔍 CONFIGURACIONES A MODIFICAR:"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

echo "1️⃣  VARIABLES DE ENTORNO EN JENKINSFILE:"
echo ""
echo "   ACTUAL                              →  PROPUESTO"
echo "   ────────────────────────────────────────────────────────────────────────"
echo "   DEPLOY_BRANCH = 'feature'           →  'develop'"
echo "   SERVER_IP = '206.62.139.100'        →  'localhost' (si opción A)"
echo "   SERVER_USER = 'l4bs'                →  'jenkins' (si opción A)"
echo "   PROJECT_PATH = '/home/l4bsb/...'    →  '/var/lib/jenkins/workspace/...'"
echo ""

echo "2️⃣  DOCKER-COMPOSE.YML:"
echo ""
echo "   ⚠️  El servicio 'api' está COMPLETAMENTE COMENTADO"
echo "   ✅ DEBE descomentarse para que el deploy funcione"
echo "   ✅ PostgreSQL está activo y funcionando correctamente"
echo ""

echo "3️⃣  ARCHIVO .ENV REQUERIDO:"
echo ""
echo "   📋 Variables necesarias (28 variables):"
echo "      • DB_NAME, DB_USER, DB_PASSWORD (base de datos)"
echo "      • JWT_SECRET, JWT_REFRESH_SECRET (autenticación)"
echo "      • EMAIL_HOST, EMAIL_USER, EMAIL_PASS (correo)"
echo "      • NODE_ENV, PORT, APP_URL (aplicación)"
echo "      • CORS_ORIGIN, BCRYPT_ROUNDS (seguridad)"
echo "      • RATE_LIMIT_* (limitación de peticiones)"
echo "      • LOG_LEVEL (logging)"
echo ""

echo "4️⃣  CREDENCIALES EN JENKINS:"
echo ""
echo "   Si repo es PRIVADO:"
echo "   • Tipo: Username with password"
echo "   • ID: 'github-credentials'"
echo "   • Username: mike7019"
echo "   • Password: <GitHub Personal Access Token>"
echo ""
echo "   Si deploy es REMOTO (Opción B):"
echo "   • Tipo: SSH Username with private key"
echo "   • ID: 'servidor-produccion-ssh'"
echo "   • Username: l4bs"
echo "   • Private Key: <SSH private key>"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo "📝 STAGES DEL PIPELINE PROPUESTO:"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

echo "  1. 🧹 Cleanup Workspace       - Limpia workspace de Jenkins"
echo "  2. 📥 Checkout                - Clona rama 'develop' desde GitHub"
echo "  3. 🔍 Verify Environment      - Verifica .env y docker-compose.yml"
echo "  4. 🛑 Stop Containers         - Detiene contenedores actuales"
echo "  5. 🏗️  Build Images            - docker-compose build --no-cache api"
echo "  6. 🚀 Deploy Containers       - docker-compose up -d"
echo "  7. 🏥 Health Check            - Verifica /api/health endpoint"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo "❓ PREGUNTAS DE CONFIRMACIÓN (necesito que respondas):"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

echo "1. ¿Qué opción prefieres?"
echo "   [ ] A - Jenkins y Docker en la misma máquina (MÁS SIMPLE)"
echo "   [ ] B - Jenkins local → Deploy remoto a 206.62.139.100"
echo ""

echo "2. ¿Tu repositorio GitHub es público o privado?"
echo "   [ ] Público (no necesita credenciales)"
echo "   [ ] Privado (necesita GitHub token)"
echo ""

echo "3. ¿Dónde están las variables de entorno?"
echo "   [ ] En .bashrc del servidor (necesito copiarlas)"
echo "   [ ] Tengo archivo .env listo"
echo "   [ ] Necesito crearlas desde cero"
echo ""

echo "4. ¿PostgreSQL debe ser en Docker o externo?"
echo "   [ ] PostgreSQL en Docker (mismo docker-compose)"
echo "   [ ] PostgreSQL externo en 206.62.139.100:5433"
echo ""

echo "5. ¿Qué rama desplegar?"
echo "   [ ] develop (desarrollo continuo)"
echo "   [ ] main (producción)"
echo ""

echo "6. ¿Jenkins tiene permisos Docker?"
echo "   [ ] Sí, ya configurado"
echo "   [ ] No, necesito comandos para configurarlo"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo "📦 ARCHIVOS QUE RECIBIRÁS DESPUÉS DE TU CONFIRMACIÓN:"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

echo "  ✅ jenkinsfile (actualizado con tu configuración)"
echo "  ✅ docker-compose.yml (con servicio API activo)"
echo "  ✅ .env.example (plantilla de variables)"
echo "  ✅ setup-jenkins.sh (script de configuración)"
echo "  ✅ test-deployment.sh (script de prueba)"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Documento completo en: JENKINS_DEPLOYMENT_PLAN.md"
echo ""
echo "💬 Responde las 6 preguntas para continuar con la configuración"
echo ""
